# Generated by Django 4.1 on 2022-12-29 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodbank', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=6)),
                ('approvedLimit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creditScore', models.IntegerField()),
                ('estimatedDebt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yearlyIncome', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userCreditApp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
