# Generated by Django 4.1 on 2022-12-29 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodbank', '0004_creditapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditaccountNumber', models.CharField(max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creditLimit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cardNumber', models.CharField(max_length=200)),
                ('applicationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditAccount', to='goodbank.creditapp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userCreditAcc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
