# Generated by Django 4.1 on 2022-12-29 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodbank', '0005_creditaccounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(max_length=800)),
                ('transactionType', models.CharField(max_length=10)),
                ('accountNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountTransaction', to='goodbank.accounts')),
                ('cardNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardTransaction', to='goodbank.creditaccounts')),
            ],
        ),
    ]
